spring:
datasource:
username: firstTask
password: firstTaskPass
url: jdbc:h2:mem:dbname:first-task?useSSL=false&?characterEncoding=utf8?createDatabaseIfNotExist=true
driver-class-name: org.h2.Driver
jpa:
properties:
hibernate:
dialect: org.hibernate.dialect.H2Dialect
ddl-auto: update


server:
  port: 9099

springfox:
  documentation:
    swagger:
      v2:
        host: junior.balinasoft.com

project:
  url: https://junior.balinasoft.com
  security:
    access-token:
      length: 64
      symbols: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
      max-count: 10
  image-folder: /first-task/images

logging:
  path: /first-task/log
